# Site settings
title: 
email: d2curro@ryerson.ca
description: > # this means to ignore newlines until "baseurl:"
  I am currently working on action recognition and pose esimation, using neural networks and deep learning.
  I am also interested in object detection and instance based semantic segmentation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dcurro.com" # the base hostname & protocol for your site
github_username:  dcurro

# Build settings
markdown: kramdown
